# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
template:
  restore-bundle: &restore-bundle
    restore_cache:
      key: gem-bundle-{{ checksum "Gemfile.lock" }}-v2
  install-dependencies: &install-dependencies
    run:
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle

  save-bundle: &save-bundle
    save_cache:
      paths:
        - ./vendor/bundle
      key: gem-bundle-{{ checksum "Gemfile.lock" }}-v2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3-node
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - <<: *restore-bundle
      - <<: *install-dependencies
      - <<: *save-bundle

      - run:
          name: run tests
          command: |
            cd janus/git && bundle exec rspec spec
  deploy:
    docker:
      - image: cimg/ruby:2.7.3-node
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *restore-bundle
      - <<: *install-dependencies
      - run: sudo apt update -y && sudo apt install python3-pip -y && pip3 install git-filter-repo
      - run: bundle exec bin/release release-to https://$public_repo_token@github.com/remitano/janus-plus-oss.git

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
