# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.3-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "janus/git/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd janus/git && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./janus/git/vendor/bundle
          key: v1-dependencies-{{ checksum "janus/git/Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            cd janus/git && bundle exec rspec spec
